apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::793131405956:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VORUVFGCHNK2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::793131405956:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-17T19:33:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1618"
  uid: 8a2e8c1b-63cb-4fe1-b03b-d62f928e8612
